services:
  - type: web
    name: stock-trading-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.lock
    startCommand: bash render_start.sh
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: CREATE_DB
        value: "true"
      - key: RESET_DB
        value: "false"
      - key: DB_PATH
        value: "/tmp/stocks.db"
